import json
import pandas as pd
import sys

# Path to the JSON file generated by RUNQAAUDIT
qa_json_path = sys.argv[1]  # pass the path as the first command-line argument

# Load the issues into a DataFrame
with open(qa_json_path, "r", encoding="utf-8") as f:
    issues = json.load(f)

df = pd.DataFrame(issues)

# Count issues by type
summary = df["Type"].value_counts().reset_index()
summary.columns = ["IssueType", "Count"]

# Save a detailed CSV and a summary CSV
detailed_csv_path = qa_json_path.replace(".json", "_detailed.csv")
summary_csv_path  = qa_json_path.replace(".json", "_summary.csv")
df.to_csv(detailed_csv_path, index=False)
summary.to_csv(summary_csv_path, index=False)

print(f"Detailed report saved to {detailed_csv_path}")
print(f"Summary report saved to {summary_csv_path}")
